<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DataBoundFile.aspx.cs" Inherits="WebProject.DataBoundFile" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title> www.DataBoundFile</title>
    <style type="text/css">
body 
{ 
    font-family: Tahoma; 

} 
    </style> 
    </head> 
    <body> 
        <form id="form1" runat="server"> 
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a >
                <asp:LinkButton ID="lnkbtnSignUp" runat="server" ForeColor="BlueViolet" Text="LogOut" Font-Bold="true" OnClick="lnkbtnSignUp_Click" ></asp:LinkButton>
            </a>
            <div style=" text-align: center; font-family: Tahoma; font-size: 25px; padding: 5px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Data Base Information&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Label ID="lbluser" runat="server" Text="Login User :" Font-Size="Medium"></asp:Label>
        <asp:Label ID="lblStatus" runat="server" Font-Size="Medium"></asp:Label>
            </div> 
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AllowPaging="true" PageSize="10" AllowSorting="true" DataKeyNames="UserName" Width="100%" BackColor="White" BorderColor="Green" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Both" OnRowEditing="GridView1_RowEditing" AutoGenerateDeleteButton="false" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowUpdating="GridView1_RowUpdating" OnRowDeleting="GridView1_RowDeleting"> 
                <Columns> 
                    <asp:TemplateField HeaderStyle-Width="10%"> 
                    <ItemTemplate> 
                        <asp:LinkButton ID="lnkBtnEdit" runat="server" Text="Edit" ToolTip="Edit Record" CommandName="Edit">
                        </asp:LinkButton> &nbsp; 
                        
                    </ItemTemplate> 
                    <EditItemTemplate> 
                        <asp:LinkButton ID="lnkBtnUpdate" runat="server" Text="Update" CommandName="Update" ToolTip="Update Record"></asp:LinkButton> &nbsp; <asp:LinkButton ID="lnkBtnCancel" runat="server" Text="Cancel" CommandName="Cancel" ToolTip="Cancel Editing"></asp:LinkButton>
                    </EditItemTemplate> 
                          </asp:TemplateField> 
                    <asp:TemplateField HeaderStyle-Width="10%"> 
                    <ItemTemplate> 
                        <asp:LinkButton ID="lnlBtnDelete" runat="server" Text="Delete" ToolTip="Delete Record" CommandName="Delete" OnClientClick="return confirm('Are You Sure? Do You Want to Delete The Record?');" CommandArgument='<%# Eval("UserName") %>'>
                            
                        </asp:LinkButton> 
                        </ItemTemplate> 
                            </asp:TemplateField>

                    <asp:TemplateField HeaderText="UserName" SortExpression="UserName">
                        <ItemTemplate> 
                            <%# Eval("UserName") %> 
                        </ItemTemplate> 
                        <EditItemTemplate> 
                            <asp:Label ID="lblUserName" runat="server" Text='<%# Eval("UserName") %>'></asp:Label>
                        </EditItemTemplate> 
                    </asp:TemplateField> 

                    <asp:TemplateField HeaderText="Password" SortExpression="Password">
                        <ItemTemplate> <%# Eval("Password") %> </ItemTemplate> 
                        <EditItemTemplate> 
                            <asp:TextBox ID="txtpsw" runat="server" Text='<%# Eval("Password") %>'></asp:TextBox>
                        </EditItemTemplate> 
                    </asp:TemplateField> 

                    <asp:TemplateField HeaderText="Name" SortExpression="Name"> 
                        <ItemTemplate> <%# Eval("Name") %> 
                        </ItemTemplate> 
                        <EditItemTemplate> 
                <asp:TextBox ID="txtName" runat="server" Text='<%# Eval("Name" )%>'></asp:TextBox>
                        </EditItemTemplate> 
                    </asp:TemplateField> 

                    <asp:TemplateField HeaderText="MobileNo" SortExpression="MobileNo">
                         <ItemTemplate> <%# Eval("MobileNo") %> 
                         </ItemTemplate> 
                        <EditItemTemplate> 
             <asp:TextBox ID="txtmobile" runat="server" Text='<%# Eval("MobileNo") %>'></asp:TextBox> 
                        </EditItemTemplate> 
                    </asp:TemplateField> 

                    <asp:TemplateField HeaderText="EmailId" SortExpression="EmailId"> 
                        <ItemTemplate> <%# Eval("EmailId") %> 
                        </ItemTemplate> 
                        <EditItemTemplate> 
                <asp:TextBox ID="txtemail" runat="server" Text='<%# Eval("EmailId" )%>'></asp:TextBox>
                        </EditItemTemplate> 
                    </asp:TemplateField>
                </Columns> 
                <%--<AlternatingRowStyle BackColor="#CCCCCC" /> <EmptyDataRowStyle BorderColor="Red" BorderStyle="Solid" ForeColor="Red"></EmptyDataRowStyle> <FooterStyle BackColor="#CCCCCC" /> <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" HorizontalAlign="Left" /> <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" /> <SortedAscendingCellStyle BackColor="#F1F1F1" /> <SortedAscendingHeaderStyle BackColor="#808080" /> <SortedDescendingCellStyle BackColor="#CAC9C9" /> 
                <SortedDescendingHeaderStyle BackColor="#383838" /> --%>
            </asp:GridView> 
        </form>
        </body>
    </html>